substitutions:
  name: "seeedstudio-mr60bha2-kit"
  friendly_name: "Seeed Studio MR60BHA2 Kit"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  flash_size: 4MB # upload.flash_size
  framework:
    type: esp-idf

# Enable Home Assistant API
api:
  encryption:
    key: "YOUR_KEY"

ota:
  - platform: esphome
    password: "YOUR_PASSWORD"
 
external_components:
  - source:
      type: git
      url: https://github.com/BersteinMilza/MR60BHA2_ESPHome_external_components
      ref: main
    components: [ seeed_mr60bha2 ]
    refresh: 0s

# Enable logging
logger:
  hardware_uart: USB_SERIAL_JTAG
  level: DEBUG

wifi:
  networks:
    - ssid: !secret wifi_ssid_1
      password: !secret wifi_password
    - ssid: !secret wifi_ssid_2
      password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ld2450 001 FH"
    password: "Config_Me"

captive_portal:

web_server:
  port: 80
  version: 3

light:
  - platform: esp32_rmt_led_strip
    id: led_ring
    name: "Seeed MR60BHA2 RGB Light"
    pin: GPIO1
    num_leds: 1
    rgb_order: GRB
    chipset: ws2812

i2c:
  sda: GPIO22
  scl: GPIO23
  scan: true
  id: bus_a

uart:
  id: uart_bus
  baud_rate: 115200
  rx_pin: 17
  tx_pin: 16
  parity: NONE
  stop_bits: 1

seeed_mr60bha2:
  id: my_seeed_mr60bha2

binary_sensor:
  - platform: seeed_mr60bha2
    has_target:
      name: "Person Information"

sensor:
  - platform: bh1750
    name: "Seeed MR60BHA2 Illuminance"
    address: 0x23
    update_interval: 60s
  - platform: seeed_mr60bha2
    breath_rate:
      name: "Real-time respiratory rate"
      filters:
          - delta: 1.0
    heart_rate:
      name: "Real-time heart rate"
      filters:
          - delta: 1.0
    distance:
      name: "Distance to detection object"
      filters:
          - round_to_multiple_of: 0.1
          - delta: 0.1
    num_targets:
      name: "Target Number"
      filters:
          - delta: 1.0
    total_phase:
      name: "Total Phase"
      filters:
          - round_to_multiple_of: 0.05
          - delta: 0.05
    breath_phase:
      name: "Breath Phase"
      filters:
          - round_to_multiple_of: 0.05
          - delta: 0.05 
    heart_phase:
      name: "Heart Phase"
      filters:
          - round_to_multiple_of: 0.05
          - delta: 0.05 
    target_1:
      x:
        name: "Target 1 X"
        filters:
          - round_to_multiple_of: 0.1
          - delta: 0.1
      y:
        name: "Target 1 Y"
        filters:
          - round_to_multiple_of: 0.1
          - delta: 0.1
    target_2:
      x:
        name: "Target 2 X"
        filters:
          - round_to_multiple_of: 0.1
          - delta: 0.1
      y:
        name: "Target 2 Y"
        filters:
          - round_to_multiple_of: 0.1
          - delta: 0.1
    target_3:
      x:
        name: "Target 3 X"
        filters:
          - round_to_multiple_of: 0.1
          - delta: 0.1
      y:
        name: "Target 3 Y"
        filters:
          - round_to_multiple_of: 0.1
          - delta: 0.1

text_sensor:
  - platform: seeed_mr60bha2
    firmware_version:
      name: "Firmware Version"
